title = "Doks"
titleSeparator = "-"
titleAddition = "Modern Hugo Documentation Starter"
description = "Hugo starter helping you build modern documentation websites."
images = ["image-doks.png"]
twitterSite = "@henkverlinde"
twitterCreator = "@henkverlinde"
ogLocale = "en_US"
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/getdoks"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaSection = "news"
siteLinksSearchBox = false

themeColor = "#fff"

# googleAnalytics = "UA-99999999-1"

quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 700, 500]
portraitPhotoWidths = [1500, 1000, 750]
lqipWidth = "20x"

footer = "© 2020 Henk Verlinde - MIT License"
version = "v0.1.0"
