dist: xenial
sudo: required

language: node_js
node_js:
  - "lts/*"
  - "14"

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb
  - yarn install

script:
  - hugo version
  - yarn test
  - yarn clean
  - yarn build

env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.75.1