[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.75.1"
  NODE_VERSION = "14.12.0"
  NPM_VERSION = "6.14.8"
  YARN_VERSION = "1.22.5"

[context.production]
  command = "hugo -b $URL --gc --minify && npm run build:functions"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"
