[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.3.0"
  NPM_VERSION = "7.16.0"

[context.production]
  command = "exec-bin bin/hugo/hugo --gc --minify"

[context.deploy-preview]
  command = "exec-bin bin/hugo/hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "exec-bin bin/hugo/hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next]
  command = "exec-bin bin/hugo/hugo --gc --minify"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "shx rm -rf public resources && exec-bin bin/hugo/hugo server --bind=0.0.0.0 --disableFastRender"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
