[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.80.0"
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "hugo -b $URL --gc && npm run build:functions"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc"
